name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "luajit", "luajit-openresty"]
        include:
          - luaVersion: "luajit"
            runtestArgs: "LUA_INCLUDE_DIR=.lua/include/luajit-2.1"
            runtestEnv: "SKIP_CMAKE=1"
          - luaVersion: "luajit-openresty"
            runtestArgs: "LUA_INCLUDE_DIR=.lua/include/luajit-2.1"
            runtestEnv: "SKIP_CMAKE=1"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v3
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v2

    - name: test
      run: |
        LUA_DIR=.lua ${{ matrix.runtestEnv }} ./runtests.sh PREFIX=.lua ${{ matrix.runtestArgs }}

    - name: build
      run: |
        luarocks make

